"""initial_schema

Revision ID: 103e08982e11
Revises: 
Create Date: 2026-04-17 09:50:40.020631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103e08982e11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_batches', sa.Column('model_version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prediction_batches_model_version_id'), 'prediction_batches', ['model_version_id'], unique=False)
    op.create_foreign_key(None, 'prediction_batches', 'model_versions', ['model_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prediction_batches', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_batches_model_version_id'), table_name='prediction_batches')
    op.drop_column('prediction_batches', 'model_version_id')
    # ### end Alembic commands ###
